bizna/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name="index"),
    
    # Companies Urls
    url(r'^add_company/$', views.CompanyCreateView.as_view(), name="add-company"),
    url(r'^company_list/$', views.CompanyCreateView.as_view(), name="list-company"),
)

kampuni/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('bizna.urls', namespace="bizna")),
    
    # User Authentication
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls', namespace='accounts')), 
       
)

bizna/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from .utils import unique_slugify

class Company(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    category = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="images/")
    country = models.CharField(max_length=255)
    province = models.CharField(max_length=255)
    county = models.CharField(max_length=255)
    district = models.CharField(max_length=255)
    city =  models.CharField(max_length=255)
    town = models.CharField(max_length=255)
    description = models.TextField()
    date_established = models.DateTimeField()
    created_by = models.ForeignKey(User)
    official_website = models.URLField(null=True, blank=True)
    
    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ['name',]
    
    def __unicode__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('index', kwargs={'slug': self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug_str = '%s' % self.name
            unique_slugify(self, slug_str)
        super(Company, self).save(*args, **kwargs)
        
        
class Events(models.Model):
    name = models.CharField(max_length=255)
    company = models.OneToOneField(Company)
    pub_date = models.DateTimeField(auto_now_add=True)
    event_date = models.DateTimeField()
    event_logo = models.ImageField(upload_to="images")
    venue = models.CharField(max_length=255)
    description = models.TextField()
    
    def __unicode__(self):
        return self.name
    

bizna/forms.py
from django import forms

from .models import Company, Events

class CompanyCreateForm(forms.ModelForm):
        
    class Meta:
        model = Company
        fields = ('name', 'category', 'logo', 'country', 'province',
            'district', 'city', 'town', 'date_established',
            'official_website','description')
        

bizna/views.py
from django.views import generic

from .models import Company, Events
from .forms import CompanyCreateForm

# Company Classes
class IndexView(generic.TemplateView):
    template_name = 'index.html'

class CompanyCreateView(generic.CreateView):
    model = Company
    form_class = CompanyCreateForm
    template_name = 'company_form'
    
    def form_valid(self, form):
        if form.is_valid():
            company = form.save(commit=False)
            company.created_by = self.request.user
            company.save()
        return super(CompanyCreateView, self).form_valid(form)
    
class KampuniListView(generic.ListView):
    model = Company
    template_name = 'company_list'
    
    def get_queryset(self):
        return Company.objects.all()
    
# Events Classes

class EventCreateView(generic.CreateView):
    model = Events
    template_name = 'event_form'
    
class EventListView(generic.ListView):
    model = Events
    template_name = 'event_list'
    
    def get_queryset(self):
        return Events.objects.order_by(Company)
    

templates/_layouts/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("Kampuni") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% block meta %}
  {% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
    
  <link rel="stylesheet" href="{% static 'css/app.css' %}">

 
   <link href="{% static 'css/justified-nav.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->

  <script src="{% static 'js/libs/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    {% load i18n %}
        {{ form.media }}
</head>
<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <div class="container">

      <div class="masthead">
          <h3 class="text-muted">Kampuni</h3>
          <ul class="nav nav-justified">
            <li><a href="{% url 'bizna:index' %}">Home</a></li>
                {% if user.is_authenticated %}            
            <li class="current_page_item">
                <a href="#"><strong>{% filter force_escape %}
                    {% firstof user.get_short_name user.get_username %}{% endfilter %}
                </strong></a></li>
            <li><a href="{% url 'bizna:add-company' %}">{% trans 'Add Listing' %}</a></li>
             <li><a href="{% url 'bizna:list-company' %}">Companies</a></li>
            <li><a href="#">{% trans 'Profile' %}</a></li>
            <li><a href="#">{% trans 'Projects' %}</a></li>
            <li><a href="#">{% trans 'Inbox' %}</a></li>
            <li><a href="{% url 'accounts:account_logout' %}">{% trans 'Logout' %}</a></li>
                {% else %}
            <li><a href="#">{% trans 'FAQs' %}</a></li>
            <li><a href="{% url 'accounts:account_login' %}">{% trans 'Login' %}</a></li>
            <li><a href="{% url 'accounts:account_signup' %}">{% trans 'Register' %}</a></li>
                {% endif %}
          </ul>
      </div>
  <header>
    {% block header %}{% endblock %}
  </header>
    
  <div role="main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    <div class="container">
      <hr>
      <p>&copy; Kampuni 2013</p>
    </div>
    {% endblock footer %}
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.9.1.min.js"><\/script>')</script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <!-- scripts concatenated and minified via django-compressor -->
  
  {% block js %}
  <script src="{% static 'js/main.js' %}"></script>
  {% endblock js %}
 
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
 
{% endblock %}
</body>
</html>

templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("Kampuni") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% block meta %}
  {% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
    
  <link rel="stylesheet" href="{% static 'css/app.css' %}">

 
   <link href="{% static 'css/justified-nav.css' %}" rel="stylesheet">
  {% block css %}{% endblock %}

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->

  <script src="{% static 'js/libs/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    {% load i18n %}
        {{ form.media }}
</head>
<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <div class="container">

      <div class="masthead">
          <h3 class="text-muted">Kampuni</h3>
          <ul class="nav nav-justified">
            <li><a href="{% url 'bizna:index' %}">Home</a></li>
            <li><a href="{% url 'bizna:list-company' %}">Companies</a></li>
                {% if user.is_authenticated %}            
            <li class="current_page_item">
                <a href="#"><strong>{% filter force_escape %}
                    {% firstof user.get_short_name user.get_username %}{% endfilter %}
                </strong></a></li>
            <li><a href="#">{% trans 'DashBord' %}</a></li>
            <li><a href="#">{% trans 'Profile' %}</a></li>
            <li><a href="#">{% trans 'Projects' %}</a></li>
            <li><a href="#">{% trans 'Inbox' %}</a></li>
            <li><a href="{% url 'accounts:account_logout' %}">{% trans 'Logout' %}</a></li>
                {% else %}
            <li><a href="#">{% trans 'FAQs' %}</a></li>
            <li><a href="{% url 'accounts:account_login' %}">{% trans 'Login' %}</a></li>
            <li><a href="{% url 'accounts:account_signup' %}">{% trans 'Register' %}</a></li>
                {% endif %}
          </ul>
      </div>
  <header>
    {% block header %}{% endblock %}
  </header>
    
  <div role="main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    <div class="container">
      <hr>
      <p>&copy; Kampuni 2013</p>
    </div>
    {% endblock footer %}
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.9.1.min.js"><\/script>')</script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <!-- scripts concatenated and minified via django-compressor -->
  
  {% block js %}
  <script src="{% static 'js/main.js' %}"></script>
  {% endblock js %}
 
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
 
{% endblock %}
</body>
</html>

templates/bizna/company_form.html
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

templates/bizna/companylist.html
{% extends "_layouts/base.html" %}


{% block content %}
{% for object in object_list %}
    <li><a href="#">{{ object.name }}</a>
        
    </li>
{% endfor %}

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block css %}
{{ block.super }}

{% endblock css %}

{% block page_title %}Kampuni - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
  
      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Get Noticed!</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <!-- Site footer -->
      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>
       <!-- /container -->


   {% endblock %}